### PR TITLE
Dont check expanded alias in _check_git_aliases

### LINKED ISSUE #29: [Bug?] Tricky alias behavior triggers bad recommendations
image

`gl` is the an alias for `git pull`, built in zsh.
I actually have no idea where `pd` and `pul` are derived for, but a simple check for the length of the string can show that I have typed a shorter options than both.

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Fixes #29 
@selfish could you check this branch works for you?

### CODE REVIEW

**Comment by selfish** [comment]
After terminal restart, still looks the same =\

image

**Comment by MichaelAquilina** [comment]
That's #30 which I havent fixed yet :) 

This bug fix is for #29

**Comment by selfish** [comment]
Whoopsie, my mistake. Works like a charm.
Thank you!

**Comment by MichaelAquilina** [comment]
Will work on #30 as soon as I find some free time :)

**Pull request merged**
