### PR TITLE
add failing test

### PR DESCRIPTION
**Pull request by benwaffle**
issue #79

### CODE REVIEW

**Comment by benwaffle** [comment]
:( i was hoping circleci would run. @MichaelAquilina can you run it?

**Comment by MichaelAquilina** [comment]
That's strange. Will see what's going on

**Comment by MichaelAquilina** [comment]
@benwaffle I've enabled builing on forked pull requests. Could you try `git commit --amend` and then `git push -f`?

**Comment by benwaffle** [comment]
no build :(

**Comment by MichaelAquilina** [comment]
Building now :)

**Comment by benwaffle** [comment]
Does that give you enough info to reproduce the bug?

**Comment by MichaelAquilina** [comment]
yes @benwaffle thanks for the PR. I'll merge this in and use it to investigate

**Pull request merged**
