### PR TITLE
Use tput

### PR DESCRIPTION
**Pull request by MichaelAquilina**

### CODE REVIEW

**Comment by ypconstante** [comment]
I'm getting an error while starting zsh 
```
/home/ypconstante/.local/share/zsh/zgen/MichaelAquilina/zsh-you-should-use-master/you-should-use.plugin.zsh:5: command not found: !tput

**Comment by MichaelAquilina** [comment]
Hi there @ypconstante. Thanks for reporting. Will take a look immediately

**Comment by MichaelAquilina** [comment]
@ypconstante what OS are you running on? Quite odd you dont have tput installed. From what I can tell despite that error message - you should use should still be working as normal correct? (I just need to suppress the warning)

**Comment by MichaelAquilina** [comment]
Uploaded 0.7.1 if you could check it out

**Comment by ypconstante** [comment]
It's a mint 19, and `tput` is available. 
Adding a space between `!` and `tput`  solves the error.

```
which tput: /usr/bin/tput
/home/ypconstante/.local/share/zsh/zgen/MichaelAquilina/zsh-you-should-use-master/you-should-use.plugin.zsh:5: command not found: !tput

```

**Comment by ypconstante** [comment]
The final solution for me was `if ! type "tput" > /dev/null; then`, just adding a space between between `!` and `tput` was showing the version in the terminal.

**Comment by MichaelAquilina** [comment]
Interesting that this does not fail for me locally (opensuse) and on CircleCI (Ubuntu).

What version of zsh are you on?

**Comment by MichaelAquilina** [comment]
Interestingly, adding a space on my system between ! and tput causes it not to work correctly anymore.

**Comment by MichaelAquilina** [comment]
Ok updated. Could you test out the latest version?

**Comment by ypconstante** [comment]
It's the latest version available to mint`zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`.
With the latest version everything is working as expected, thanks!

**Pull request merged**
