### PR TITLE
"disabling aliases" renamed to "disabling hints"

### PR DESCRIPTION
**Pull request by chrisgrieser**
The phrasing of "disabling" aliases is quite confusing, at first I thought it would turn the aliases completely off, which it does not. I changed the wording to "ignore aliases" to make the feature more clear.

Great little tool btw, thanks a lot for it!

### CODE REVIEW

**Comment by MichaelAquilina** [comment]
I can see how "disabling aliases" is actually quite confusing. But I'm not sure "ignoring aliases" is any better.

Maybe "disable_alias_hints"?

**Comment by chrisgrieser** [comment]
good point, I fixed it

**Review by MichaelAquilina — COMMENTED** [review]
looks good :) please take a look at why the lint check is failing and update based on that.

Should be good to go after!

**Comment by chrisgrieser** [comment]
Ah, first time encountering `.rst`, sorry! But found the issue, lint check passes now.

**Review by MichaelAquilina — APPROVED** [review]

**Comment by MichaelAquilina** [comment]
Thanks for the PR @chrisgrieser :)

**Pull request merged**
